config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # Connect Site
  resource :facebook, :except => :create do
    get :callback, :to => :create
  end

  resource :welcome, controller: "welcome", only: [:index] do
    get :analytics
  end

  root 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(admin)
    # Define abilities for the passed in user here. For example:
    #
      admin ||= Admin.new # guest user (not logged in)
      if admin.has_role? :super_admin
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/arsenal.rb
class Arsenal < Settingslogic
  source "#{Rails.root}/config/arsenal.yml"
  namespace Rails.env

  def all_keys
    Arsenal.players.values.map{|v| v.values}.flatten.uniq.compact + self.keywords + self.clubs
  end

  def predict(str)
    self.all_keys.map{|keyword| str.scan(keyword).count }.sum
  end
end

app/models/facebook.rb
class Facebook < ActiveRecord::Base
  def profile
    @profile ||= FbGraph::User.me(self.access_token).fetch
  end

  class << self
    def config
      @config ||= if ENV['fb_client_id'] && ENV['fb_client_secret'] && ENV['fb_scope'] && ENV['fb_canvas_url']
        {
          :client_id     => ENV['fb_client_id'],
          :client_secret => ENV['fb_client_secret'],
          :scope         => ENV['fb_scope'],
          :canvas_url    => ENV['fb_canvas_url']
        }
      else
        YAML.load_file("#{Rails.root}/config/facebook.yml")[Rails.env].symbolize_keys
      end
    rescue Errno::ENOENT => e
      raise StandardError.new("config/facebook.yml could not be loaded.")
    end

    def app
      FbGraph::Application.new config[:client_id], :secret => config[:client_secret]
    end

    def auth(redirect_uri = nil)
      FbGraph::Auth.new config[:client_id], config[:client_secret], :redirect_uri => redirect_uri
    end

    def identify(fb_user)
      _fb_user_ = find_or_initialize_by(identifier: fb_user.identifier.try(:to_s))
      _fb_user_.access_token = fb_user.access_token.access_token
      _fb_user_.save!
      _fb_user_
    end
  end
end

app/models/result.rb
class Result < ActiveRecord::Base

  def prediction
    return unless self.identifier
    me = FbGraph::User.me(Facebook.find_by(identifier: self.identifier).access_token).fetch
    self.profile_score = Arsenal.predict(me.inspect.downcase)
    self.post_score = Arsenal.predict(me.posts.inspect.downcase)
    self.feed_score = Arsenal.predict(me.feed.inspect.downcase)
    self.save
    self
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :admins, :join_table => :admins_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  protect_from_forgery with: :exception

  rescue_from FbGraph::Exception, :with => :fb_graph_exception

  # before_action :authenticate_admin!

  def fb_graph_exception(e)
    flash[:error] = {
      :title   => e.class,
      :message => e.message
    }
    current_user.try(:destroy)
    redirect_to root_url
  end
end

app/controllers/facebooks_controller.rb
require 'rack/oauth2'

class FacebooksController < ApplicationController
  before_filter :require_authentication, :only => :destroy

  rescue_from Rack::OAuth2::Client::Error, :with => :oauth2_error

  # handle Facebook Auth Cookie generated by JavaScript SDK
  def show
    auth = Facebook.auth.from_cookie(cookies)
    authenticate Facebook.identify(auth.user)
    redirect_to root_url
  end

  # handle Normal OAuth flow: start
  def new
    client = Facebook.auth(callback_facebook_url).client
    redirect_to client.authorization_uri(
      :scope => Facebook.config[:scope]
    )
  end

  # handle Normal OAuth flow: callback
  def create
    client = Facebook.auth(callback_facebook_url).client
    client.authorization_code = params[:code]
    access_token = client.access_token! :client_auth_body
    user = FbGraph::User.me(access_token).fetch
    authenticate Facebook.identify(user)
    redirect_to root_url
  end

  def destroy
    unauthenticate
    redirect_to root_url
  end

  private

  def oauth2_error(e)
    flash[:error] = {
      :title => e.response[:error][:type],
      :message => e.response[:error][:message]
    }
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @me = FbGraph::User.me(current_user.access_token).fetch if current_user
    @page = FbGraph::Page.new(112562602433)
  end

   def analytics
    return :back unless current_user

    @me = FbGraph::User.me(current_user.access_token).fetch if current_user
    @page = FbGraph::Page.new(112562602433)
    return :back unless @me.like?(@page)

    return if @result = Result.find_by(identifier: current_user.identifier)

    @result = Result.new(identifier: current_user.identifier).prediction
    p @me.inspect
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Authentication::HelperMethods

  def title(page_title)
    content_for(:title) { page_title.to_s }
  end

  def yield_or_default(section, default = '')
    content_for?(section) ? content_for(section) : default
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/application.html.haml
!!!
%html{ lang: I18n.locale.to_s }
  %head
    %title= yield_or_default :title, action_name.titlecase
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0' }
    %meta{ content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible' }
    = csrf_meta_tags
    = yield :head

    = stylesheet_link_tag 'application', media: 'all', data: { turbolinks_track: true }

    / Touch icon (uncomment if needed)
    / %link{ href: asset_path('apple-touch-icon-144x144.png'), rel: 'apple-touch-icon', sizes: '144x144' }

    / Placed at the top of the document 'cause of turbolinks
    = javascript_include_tag 'application', data: { turbolinks_track: true }

    /[if lte IE 8]
      = javascript_include_tag 'http://html5shim.googlecode.com/svn/trunk/html5.js', asset_path('respond.js')

  %body
    = render 'shared/navbar'

    #main-container.container
      = render 'shared/messages'
      = yield

    = render 'shared/footer'
    = render 'shared/turbolinks_spinner'

    %script{src: "http://connect.facebook.net/en_US/all.js"}
    :javascript
      FB.init({
        appId: "<%= Facebook.config[:client_id] %>",
        cookie: true,
        xfbml: true,
        oauth: true
      });

app/views/shared/_footer.html.haml
%footer
  .container
    %hr
    %p
      = link_to 'https://github.com/diowa/ruby2-rails4-bootstrap-heroku' do
        %span.fa.fa-github
        diowa/ruby2-rails4-bootstrap-heroku

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  %div{class: "alert alert-#{key} alert-warning"}
    %button.close{"data-dismiss" => "alert", href: "#"} ×
    %ul
      %li
        = value

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default{ role: 'navigation' }
  .container
    .navbar-header
      %button.navbar-toggle{ type: 'button', data: { toggle: 'collapse', target: '.navbar-collapse' } }
        %span.sr-only= t('.toggle_navigation')
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Gooner Analytics", root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to Arsenal.contact.facebook.name, Arsenal.contact.facebook.link
        %li= link_to Arsenal.contact.web.name, Arsenal.contact.web.link

app/views/shared/_sidebar.html.haml
.avatar
  %profile-pic{"facebook-logo" => "true", size: "normal", uid: current_user.try(:identifier)}

- if authenticated?
  %p= link_to "Logout", facebook_path, :method => :delete
- else
  %dl
    %dt JavaScript SDK
    %dd
      %login-button{length: "long", onlogin: "location.href = '#{facebook_path}'", scope: Facebook.config[:scope]}
    %dt Normal OAuth flow
    %dd= link_to "Start", new_facebook_path

app/views/shared/_turbolinks_spinner.html.haml
#turbolinks-spinner
  %span#turbolinks-spinner-label= t('.loading')

app/views/welcome/analytics.html.haml
%h2
  Profile :
  = @result.profile_score
  điểm
%h2
  Posts
  = @result.post_score
  điểm
%h2
  Feeds
  = @result.feed_score
  điểm

%p
  = @me.inspect

app/views/welcome/index.html.haml
- title "Gooner Analytics | Gooners.vn - Hội cổ động viên Arsenal tại Việt Nam"
%h1.text-center
  Gooner Analytics
  %small Cùng tìm chỉ số gooner của bạn.

- unless authenticated?
  %h2 Xin chào bạn, đầu tiên bạn cần đăng nhập để tiếp tục
  = link_to "Đăng nhập", new_facebook_path, class: "btn btn-primary"
- else
  %h3
    Xin chào
    = @me.name

  - unless @me.like?(@page)
    %p
      Bạn cần like page
      = link_to "Arsenal FC in Viet Nam", "https://www.facebook.com/Arsenal.FC.Vietnam"
      để tiếp tục
  - else
    %p
      Thay mặt page
      = link_to "Arsenal FC in Viet Nam", "https://www.facebook.com/Arsenal.FC.Vietnam"
      mình xin cảm ơn bạn đã luôn ủng hộ page trong thời gian qua. Chúng mình sẽ cố gắng cống hiến nhiều hơn nữa cho cộng đồng gooners Việt Nam.
    = link_to "Phân tích", analytics_welcome_path, class: "btn btn-primary"